name: 京豆昨日收益

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0,1,9 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_bean_change

jobs:
    build:
        runs-on: macos-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【测试】"
              run: |
                  node -v
                  node jdCookie.js
                  ls -a
                  echo "test"
              shell: bash {0}
            - name: "运行 【京豆昨日收益】"
              run: |
                  node jd_bean_sign.js
              shell: sh {0}

