name: 京豆昨日收益

on:
    workflow_dispatch:
    schedule:
        - cron:  '46 0,1,8 * * *'
#     watch:
#         types: [started]
#     repository_dispatch:
#         types: jd_bean_change

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【京豆昨日收益】"
              run: |
                  node jd_bean_sign.js

